# Generated by Django 3.2.11 on 2022-01-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('source_email', models.CharField(default='None', max_length=250)),
                ('pro_number', models.CharField(max_length=100)),
                ('loaded_miles', models.IntegerField()),
                ('pickup', models.DateTimeField()),
                ('delivery', models.DateTimeField()),
                ('no_of_additional_stops', models.IntegerField()),
                ('vehicle_size', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('max_pieces', models.IntegerField()),
                ('max_weight', models.IntegerField()),
                ('from_address', models.CharField(default='None', max_length=250)),
                ('to_address', models.CharField(default='None', max_length=250)),
                ('dimensions', models.CharField(max_length=20)),
                ('stackable', models.CharField(max_length=20)),
            ],
        ),
    ]
