# Generated by Django 3.2.11 on 2022-01-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='to_address',
        ),
    ]
