# Generated by Django 3.2.11 on 2022-01-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20220119_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='from_address',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='mail',
            name='to_address',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
