# Generated by Django 3.2.11 on 2022-01-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20220119_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='source_email',
        ),
    ]
