# Generated by Django 3.2.11 on 2022-01-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_remove_mail_source_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='source_email',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
